### PR TITLE
Add Exercise class

### PR DESCRIPTION
**Pull request by JMattChiam**
Added Exercise class to represent each exercise in a workout. 

Should suffice for now, not sure if we want to make use of the muscle info for each exercise, probably not necessary for first iteration.

### CODE REVIEW

**Review by IshaaanVyas — COMMENTED** [review]
Looks good, I agree that muscle group is not necessary for v1.0.

**Review by KishorKumar11 — COMMENTED** [review]
All good!

**Review by jonathanmui4 — COMMENTED** [review]
Looks good to me for v1 too! 👍

**Comment by qqkoh** [comment]
Yep looks good

**Pull request merged**
